export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  CART_EMPTY: 'CART_EMPTY',
  CART_HAS_ISSUES: 'CART_HAS_ISSUES',
  VOUCHER_INVALID: 'VOUCHER_INVALID',
  SHIPPING_UNAVAILABLE: 'SHIPPING_UNAVAILABLE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  ORDER_NOT_PAYABLE: 'ORDER_NOT_PAYABLE',
  PAYMENT_UNAVAILABLE: 'PAYMENT_UNAVAILABLE',
  STOCK_CHANGED: 'STOCK_CHANGED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiSuccess<T> {
  data: T;
}

export interface ApiError {
  error: {
    code: ErrorCode | (string & {});
    message: string;
  };
}

export type ApiResponse<T> = ApiSuccess<T> | ApiError;
